#!/usr/bin/env bash

python=/data/.miniforge3/envs/xepy311/bin/python
max_epochs=200


$python -m foundation_model.scripts.train --max_epochs=$max_epochs --devices=4 --shared_block_lr=0.005 --task_block_lr=0.01 --exp_name mp_1.0-shared_lr=0.005_block_lr=0.01
$python -m foundation_model.scripts.train --max_epochs=$max_epochs --devices=4 --shared_block_lr=0.005 --task_block_lr=0.05 --exp_name mp_1.0-shared_lr=0.005_block_lr=0.05
$python -m foundation_model.scripts.train --max_epochs=$max_epochs --devices=4 --shared_block_lr=0.01 --task_block_lr=0.01 --exp_name mp_1.0-shared_lr=0.01_block_lr=0.01
$python -m foundation_model.scripts.train --max_epochs=$max_epochs --devices=4 --shared_block_lr=0.01 --task_block_lr=0.05 --exp_name mp_1.0-shared_lr=0.01_block_lr=0.05