# Legacy task configurations extracted from model_config.py.bak
# These correspond to the 'ac_qc_starry_attrs' group.

# Define a common optimizer configuration
default_optimizer_config: &default_optimizer
  optimizer_type: "AdamW"
  lr: 0.01
  weight_decay: 0.001
  eps: 0.000001
  betas: [0.9, 0.999]
  freeze_parameters: False
  scheduler_type: "ReduceLROnPlateau"
  mode: "min"
  factor: 0.5
  patience: 5
  min_lr: 0.0001
  monitor: "train_loss"
  interval: "epoch"
  frequency: 1

tasks:
  - name: "Seebeck coefficient"
    type: REGRESSION
    enabled: True
    weight: 1.0
    dims: [64, 32, 16, 1]
    norm: True
    residual: False
    lora_enabled: False
    lora_rank: 0
    lora_alpha: 1.0
    lora_freeze_base: True
    optimizer: *default_optimizer
  - name: "Thermal conductivity"
    type: REGRESSION
    enabled: True
    weight: 1.0
    dims: [64, 32, 16, 1]
    norm: True
    residual: False
    lora_enabled: False
    lora_rank: 0
    lora_alpha: 1.0
    lora_freeze_base: True
    optimizer: *default_optimizer
  - name: "Electrical resistivity"
    type: REGRESSION
    enabled: True
    weight: 1.0
    dims: [64, 32, 16, 1]
    norm: True
    residual: False
    lora_enabled: False
    lora_rank: 0
    lora_alpha: 1.0
    lora_freeze_base: True
    optimizer: *default_optimizer
  - name: "Magnetic susceptibility"
    type: REGRESSION
    enabled: True
    weight: 1.0
    dims: [64, 32, 16, 1]
    norm: True
    residual: False
    lora_enabled: False
    lora_rank: 0
    lora_alpha: 1.0
    lora_freeze_base: True
    optimizer: *default_optimizer
  - name: "Hall coefficient"
    type: REGRESSION
    enabled: True
    weight: 1.0
    dims: [64, 32, 16, 1]
    norm: True
    residual: False
    lora_enabled: False
    lora_rank: 0
    lora_alpha: 1.0
    lora_freeze_base: True
    optimizer: *default_optimizer
  - name: "ZT"
    type: REGRESSION
    enabled: True
    weight: 1.0
    dims: [64, 32, 16, 1]
    norm: True
    residual: False
    lora_enabled: False
    lora_rank: 0
    lora_alpha: 1.0
    lora_freeze_base: True
    optimizer: *default_optimizer
  - name: "Power factor"
    type: REGRESSION
    enabled: True
    weight: 1.0
    dims: [64, 32, 16, 1]
    norm: True
    residual: False
    lora_enabled: False
    lora_rank: 0
    lora_alpha: 1.0
    lora_freeze_base: True
    optimizer: *default_optimizer
  - name: "Carrier concentration"
    type: REGRESSION
    enabled: True
    weight: 1.0
    dims: [64, 32, 16, 1]
    norm: True
    residual: False
    lora_enabled: False
    lora_rank: 0
    lora_alpha: 1.0
    lora_freeze_base: True
    optimizer: *default_optimizer
  - name: "Electrical conductivity"
    type: REGRESSION
    enabled: True
    weight: 1.0
    dims: [64, 32, 16, 1]
    norm: True
    residual: False
    lora_enabled: False
    lora_rank: 0
    lora_alpha: 1.0
    lora_freeze_base: True
    optimizer: *default_optimizer
  - name: "Thermopower"
    type: REGRESSION
    enabled: True
    weight: 1.0
    dims: [64, 32, 16, 1]
    norm: True
    residual: False
    lora_enabled: False
    lora_rank: 0
    lora_alpha: 1.0
    lora_freeze_base: True
    optimizer: *default_optimizer
  - name: "Lattice thermal conductivity"
    type: REGRESSION
    enabled: True
    weight: 1.0
    dims: [64, 32, 16, 1]
    norm: True
    residual: False
    lora_enabled: False
    lora_rank: 0
    lora_alpha: 1.0
    lora_freeze_base: True
    optimizer: *default_optimizer
  - name: "Hall mobility"
    type: REGRESSION
    enabled: True
    weight: 1.0
    dims: [64, 32, 16, 1]
    norm: True
    residual: False
    lora_enabled: False
    lora_rank: 0
    lora_alpha: 1.0
    lora_freeze_base: True
    optimizer: *default_optimizer
  - name: "Electronic contribution"
    type: REGRESSION
    enabled: True
    weight: 1.0
    dims: [64, 32, 16, 1]
    norm: True
    residual: False
    lora_enabled: False
    lora_rank: 0
    lora_alpha: 1.0
    lora_freeze_base: True
    optimizer: *default_optimizer
  - name: "Electronic thermal conductivity"
    type: REGRESSION
    enabled: True
    weight: 1.0
    dims: [64, 32, 16, 1]
    norm: True
    residual: False
    lora_enabled: False
    lora_rank: 0
    lora_alpha: 1.0
    lora_freeze_base: True
    optimizer: *default_optimizer
